import { Schema, model, Types } from "mongoose";

const userSchema = new Schema({
  firstName: { type: String, required: true },
  lastName: { type: String, required: true },
  // will be generated by the app based on first and last name
  username: { type: String, unique: true },
  email: { type: String, unique: true, required: true },
  password: { type: String, required: true },
  recoveryEmail: { type: String },
  DOB: { type: Date, required: true },
  mobileNumber: { type: String, unique: true, required: true },
  role: {
    type: String,
    enum: ["User", "Company_HR"],
    default: "User",
    required: true,
  },
  status: { type: String, enum: ["online", "offline"], default: "offline" },
  otpCode: { type: String },
});

userSchema.pre("save", async function (next) {
  // generate username
  this.username = `${this.firstName}${this.lastName}`;

  // generate formated date
  if (this.DOB) {
    const dob = new Date(this.DOB);
    const year = dob.getUTCFullYear();
    const month = dob.getUTCMonth() + 1; // Months are zero-indexed
    const day = dob.getUTCDate();
    this.DOB = `${year}-${month}-${day}`;
  }
  next();
});

const User = model("User", userSchema);
export default User;
